name: Auto Commit

on:
  schedule:
    - cron: '0 6 * * *'   # Daily 6 AM UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update File
        run: |
          echo "Last Update: $(date)" > activity.txt

      - name: Commit Changes
        run: |
          git config --global user.name "ghosh-vishnu"
          git config --global user.email "vishnu.klhs@gmail.com"
          git add .
          git commit -m "Daily auto commit" || exit 0

      - name: Push Changes
        run: git push
