name: Auto Commit

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update File
        run: |
          echo "Last Update: $(date)" > activity.txt

      - name: Commit Changes
        run: |
          git config --global user.name "ghosh-vishnu"
          git config --global user.email "vishnu.klhs@gmail.com"

          git add .
          git diff --staged --quiet || git commit -m "Daily auto commit"

      - name: Push Changes
        run: |
          git push origin main
